version: "3.6"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: '0:0'
    container_name: sqlserver2019-2
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: P@ssword123
    volumes:
      - ~/docker/sqlserver-data:/var/opt/mssql2